# Generated by Django 3.2.9 on 2021-11-24 14:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
