# Generated by Django 3.2.9 on 2021-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211124_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='future',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='learning',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='master',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficient',
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('MASTER', 'MASTER'), ('PROFICIENT', 'PROFICIENT'), ('LEARNING', 'LEARNING'), ('LEARN IN FUTURE', 'LEARN IN FUTURE')], default='LEARNING', max_length=15),
        ),
    ]
