# Generated by Django 3.2.9 on 2021-11-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211124_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='future',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficient',
            field=models.BooleanField(default=True),
        ),
    ]
