# Generated by Django 3.2.9 on 2021-11-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211124_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='current_role',
            field=models.CharField(default='Software Developer', max_length=25),
        ),
    ]
